apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: database-test-script
  labels:
    name: redis
spec:
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379