apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJrZW5uZXRoZmx5ZSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfM0tudTNtamF4WENLRkZqSXY2c1lCNmp5NnRNIiwiZW1haWwiOiJtaWxsZWZseWVAZ21haWwuY29tIiwiYXV0aCI6ImEyVnVibVYwYUdac2VXVTZaR05yY2w5d1lYUmZNMHR1ZFROdGFtRjRXRU5MUmtacVNYWTJjMWxDTm1wNU5uUk4ifX19
type: kubernetes.io/dockerconfigjson